---
title: "Data Visualisation Final Project"
author: "Study Group 11: Nereid Kwok, Nisa Ozer, Lauren Wade, Thomas Giannetti-Fakhouri, Kazmer Nagy-Betegh, Chandrime Tolia"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: true
    toc: yes
    toc_float: yes
---


```{r libraries, include=FALSE}

library(skimr)
library(vroom)
library(tidyverse)
library(dplyr)
library(ggthemes)
library(gghighlight)
library(plotly)
library(patchwork)
library(countrycode)
library(jpeg)
library(png)
library(grid)

```


```{r echo=FALSE, include=FALSE}
astronauts <- vroom('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')

launches <- vroom("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/launches.csv")

agencies <- vroom("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/agencies.csv")

mission_success <- vroom(here::here("data","Space_Corrected.csv"))
```

```{r echo=FALSE, include=FALSE}
skim(astronauts)
```


```{r echo=FALSE, include=FALSE}
skim(launches)
```


```{r echo=FALSE, include=FALSE}
skim(agencies)
```

```{r echo=FALSE, include=FALSE}
mission_success <- select(mission_success, -c(1,2))

mission_success <- mission_success %>% 
  janitor::clean_names() %>% 
  mutate(datum = as.Date(mission_success$Datum, format = "%a %b %d, %Y"))


launches <-  launches %>% 
  left_join(mission_success, by = c("launch_date" = "datum"))
```


```{r, echo=FALSE, include=FALSE}
country_names <- c(US = "United States",
                'F'  = "France",
                BR = "Brazil",
                CN = "China",
                I = "italy",      
                'I-ESA' = "European Space Agency",
                RU  = "Russia",
                IR = "Iran",
                IL = "Isreal",
                J = "Japan",
                IN = "India",
                KR = "North Korea",
                KP = "South Korea",
                SU = "Soviet Union",
                UK = "United Kingdom",
                CYM = "Cayman Islands",
                'I-ELDO' = "European Launcher Development Organisation")  


country_colors <- c(US = "blue",
                    'F'  = "skyblue",
                    BR = "limegreen",
                    CN = "red3",
                    I = "lightgreen",      
                    'I-ESA' = "plum1",
                    RU  = "tomato",
                    IR = "lightgoldenrod",
                    IL = "tan2",
                    J = "mistyrose",
                    IN = "",
                    KR = "North Korea",
                    KP = "South Korea",
                    SU = "Soviet Union",
                    UK = "United Kingdom",
                    CYM = "Cayman Islands",
                    'I-ELDO' = "European Launcher Development Organisation")



launches <- launches %>% 
  mutate(country_name = country_names[state_code])

launches <- launches %>% 
  mutate(agency = case_when(is.na(agency) ~ state_code,
                            TRUE ~ agency))

```


```{r space_race, fig.align='center', fig.height= 5, fig.width= 11, echo=FALSE}

launches %>% 
  filter(country_name == "NA")

space_race <- launches %>% 
  # filter(state_code %in% c("US", "SU", "RU")) %>% 
  group_by(launch_year, country_name) %>% 
  summarise(state_code, country_name, num_launches = n()) %>% 
  ungroup()
  


launchs_per_year_US_SU <- space_race %>% 
  filter(state_code %in% c("US", "SU", "RU")) %>% 
  ggplot( aes(x = launch_year,
              y = num_launches))+
  geom_point(aes(color = country_name))+
  geom_line(aes(color = country_name))+
  gghighlight(state_code %in% c("US","SU","RU"))+
  theme_minimal()+
  labs(title = "United States and Soviet Union (Russia) Space Race",
       x = "",
       y = "launches/year")
  # scale_color_manual(values = country_colors)



launchs_per_year_non_us_su <- space_race %>% 
  ggplot(aes(x = launch_year,
              y = num_launches))+
  geom_point(aes(color = country_name))+
  geom_line(aes(color = country_name))+
  gghighlight(!state_code %in% c("US","SU","RU"))+
  theme_minimal()+
  labs(title = "Countries joining Space Exploration",
       x = "",
       y = "launches/year")
  # scale_color_manual(values = country_colors)

launchs_per_year_US_SU | launchs_per_year_non_us_su

```

```{r space_race,  fig.align='center', fig.height= 5, fig.width= 11, echo=FALSE}

img <- readJPEG(here::here("data/milky.jpg"))

g <- rasterGrob(img, interpolate=TRUE)

space_race_dates <- space_race %>% 
  filter(state_code %in% c("US", "SU", "RU")) %>% 
  ggplot( aes(x = launch_year,
              y = num_launches))+
  geom_point(aes(color = country_name))+
  geom_line(aes(color = country_name))+
  gghighlight(state_code %in% c("US","SU","RU"))+
  theme_minimal()+
  labs(title = "1957 - 1969 Space Race",
       x = "",
       y = "launches/year")+
  annotate("rect", xmin = 1957, xmax = 1969, ymin = 0, ymax = 110,
           alpha = 0.3, fill = "skyblue")


space_race_dates
```
```{r space race success ,fig.align='center', fig.height= 5, fig.width= 11, echo=FALSE}


space_race_mission_success <- launches %>% 
  filter(state_code %in% c("US", "SU", "RU")) %>%
  filter(launch_year < 1970) %>% 
  group_by(launch_year, country_name, category) %>% 
  summarise(n_missions = n()) %>% 
  mutate(prc_missions = round(n_missions/sum(n_missions)*100,2)) %>% 
  ggplot(aes(x = country_name,
              y = n_missions))+
  geom_col(aes(fill = category))+
  geom_text(aes(x = country_name,
                y = n_missions,
                label = paste0(prc_missions,"%"),
                group = category),
            position=position_stack(vjust=0.5))+
  theme_minimal()+
  labs(title = "1957 - 1969 Space Race success Rate",
       x = "",
       y = "launches/year",
       fill = "")+
  facet_grid(~launch_year)+
  scale_fill_manual(label = c("Failed Mission", "Succesful Mission"),
                    values = c("tomato","springgreen4"))+
  theme(axis.text.x = element_text(angle= 45, ))

space_race_mission_success


age <- astronauts %>% 
  mutate(age_at_mission = year_of_mission - year_of_birth) %>% 
  select(age_at_mission, year_of_mission, year_of_birth, name)

age_first <- age %>% 
  group_by(name) %>% 
  summarise(age_at_mission = min(age_at_mission))

#age at their first mission, when they become astranauts
age_first_plot <- age_first %>% 
  ggplot(aes( x = age_at_mission )) +
  geom_histogram()+
  labs(title = "Age distribution of Astronauts on Their First Mission",
       subtitle = "Age taken for each astronaut at the time of their first mission") +
  theme_minimal()
 
age_first_plot

#general age distribution in the industry
age_plot <- age %>% 
  ggplot(aes( x = age_at_mission )) +
  geom_histogram() +
  labs(title = "Age distribution of Astronauts",
       subtitle = "Age taken for each astronaut at time of every mission") +
  theme_minimal() + 
  annotate("text", x = 77, y = 15, label = "John H. Glenn jr.", size = 4)
 
age_plot
```
```{r fig.align='center', fig.height= 5, fig.width= 11}

gender_count <- astronauts %>% 
    group_by(sex, year_of_mission) %>% 
    count(year_of_mission)

female_male <- gender_count %>% 
  ggplot(aes(x = year_of_mission, y = n, fill = sex)) +
  geom_col() +
  labs(title = "Number of Male and Female Astranouts Launched into space by year")+
  theme_minimal()
female_male_annotated <- female_male + 
  annotate("text", x = 1965, y = 25, label = "Valentina Tereshkova", size = 3) + 
  annotate("segment", x = 1965, xend = 1963, y = 23,  yend = 6, colour = "black", size = 0.5 , arrow = arrow() )

female_male_annotated


space_race_mission_success_values <- launches %>% 
  group_by(launch_year, country_name, category) %>% 
  summarise(n_missions = n()) %>% 
  mutate(mission_ssuccess_rate = round(n_missions/sum(n_missions)*100,2)) %>% 
  ungroup() %>% 
  filter(category == "O") %>% 
  select(-n_missions, -category)

launches <- launches %>% 
  left_join(space_race_mission_success_values, by = c("country_name" = "country_name","launch_year" = "launch_year"))
    
```

```{r space race key dates, fig.align='center', fig.height= 5, fig.width= 11, echo=FALSE}

img <- readJPEG(here::here("data/laika.jpg"))

g <- rasterGrob(img, interpolate=TRUE)


img <- readJPEG(here::here("data/alex.jpg"))

g2 <- rasterGrob(img, interpolate=TRUE)

img <- readJPEG(here::here("data/moon.jpg"))

g3 <- rasterGrob(img, interpolate=TRUE)

launches %>% 
  filter(state_code %in% c("US", "SU", "RU")) %>% 
  filter(launch_year < 1970) %>% 
  group_by(launch_year, country_name) %>% 
  summarise(mission_ssuccess_rate, launch_year, country_name, num_launches = n()) %>% 
  ggplot( aes(x = launch_year,
              y = num_launches,
              label = mission_ssuccess_rate))+
  
  annotate("rect", xmin = 1957, xmax = 1969, ymin = 0, ymax = 180,
           alpha = 0.3, fill = "skyblue")+
  
  annotation_custom(g, xmin=1955, xmax=1959, ymin=57, ymax=80)+
  annotate("segment", x = 1957, y = 0, xend = 1957, yend = 50 ,color = "tomato")+
  annotate("text", x = 1957, y = 55, label = "Laika in Space",color = "tomato")+
  
  annotate("segment", x = 1961, y = 0, xend = 1961, yend = 70 , color = "tomato")+
  annotate("text", x = 1961, y = 75, label = "Yuri Gagarin in Space", color = "tomato")+
  
  annotate("segment", x = 1963, y = 0, xend = 1963, yend = 90 , color = "tomato")+
  annotate("text", x = 1963, y = 95, label = "Valentina Tereshkova first woman in Space", color = "tomato")+
  
  annotation_custom(g2, xmin=1964, xmax=1966, ymin=108, ymax=128)+
  annotate("segment", x = 1965, y = 0, xend = 1965, yend = 100 , color = "tomato")+
  annotate("text", x = 1965, y = 105, label = " Alexei Leonov leaves spacecrafts and has first spacewalk", color = "tomato")+
  
  annotate("segment", x = 1967, y = 0, xend = 1967, yend = 110 , color = "black")+
  annotate("text", x = 1967, y = 115, label = "Deadliest Year for both Sides", color = "black")+
  
  annotate("segment", x = 1968, y = 0, xend = 1968, yend = 130 , color = "blue")+
  annotate("text", x = 1968, y = 132, label = "Apollo 8 first human crewed spacecraft to reach the moon, orbit, and return to earth", color = "blue", hjust = .8)+
  
  annotation_custom(g3, xmin=1968, xmax=1969, ymin=142 ,ymax=172)+
  annotate("segment", x = 1969, y = 0, xend = 1969, yend = 135 , color = "blue")+
  annotate("text", x = 1969, y = 140, label = "First men to walk on the moon - American victory", color = "blue", hjust = 1)+
  
  geom_point(aes(color = country_name))+
  geom_line(aes(color = country_name))+
  geom_text(aes(x = launch_year,
              y = num_launches,
              label = paste0(mission_ssuccess_rate,"%")),
            vjust = -1)+
  theme_minimal()+
  labs(title = "1957 - 1969 Space Race",
       subtitle = "Percentages indicate the success rate of launches in each year",
       x = "",
       y = "launches/year",
       color = "")+
  xlim(1955,1972)+
  ylim(0,180)+
  scale_x_continuous(breaks = scales::pretty_breaks(12))
  

```

```{r space walk record holders, echo=FALSE}

astronauts %>% 
  group_by(name) %>% 
  distinct(nationality, total_eva_hrs) %>% 
  ungroup() %>% 
  slice_max(order_by = total_eva_hrs, n=15, with_ties = TRUE) %>% 
  ggplot()+
  geom_col(aes(x = total_eva_hrs,
             y = reorder(name,total_eva_hrs),
             fill = nationality))+
  geom_text(aes(x = total_eva_hrs,
             y = reorder(name,total_eva_hrs),
             label = total_eva_hrs),
            hjust = 2)+
  theme_minimal()+
  labs(title = "Most Hours Spent Space Walking",
       y = "",
       x = "hours")
  
  



```


```{r}

```

US Launches 

1966: Peaked state launches
1986: Challenger Explosion
1989: Private commercial Launches starts
2012: Barely any state launches

```{r}
 launches %>% 
  filter(state_code == "US") %>% 
  mutate(agency_type = ifelse(as.character(agency_type) == "startup", "private", as.character(agency_type))) %>%  # combine startup and private
  group_by(launch_year,agency_type,category) %>% 
  count() %>% 
  unite('type_category',agency_type:category,remove=FALSE) %>% 
  mutate(type_category = case_when(type_category=="state_F" ~ "State - Failure",
                                   type_category=="state_O" ~ "State - Success",
                                   type_category=="private_F" ~ "Private - Failure",
                                   type_category=="private_O" ~ "Private - Success")) %>% 
  ggplot(aes(x=launch_year,y=n,fill = type_category))+
  geom_col(width = 0.8)+
  geom_segment(aes(x = 1966, y = 85, xend = 1966, yend = 78),color = "royalblue",
                  arrow = arrow(length = unit(0.15, "cm")))+
  geom_segment(aes(x = 1986, y = 40, xend = 1986, yend = 20),color = "indianred",
                  arrow = arrow(length = unit(0.15, "cm")))+
  geom_segment(aes(x = 1988.5, y = 60, xend = 1988.5, yend = 20),color = "grey40",
                  arrow = arrow(length = unit(0.15, "cm")))+
  geom_segment(aes(x = 2012, y = 42, xend = 2012, yend = 20),color = "royalblue",
                  arrow = arrow(length = unit(0.15, "cm")))+
  annotate("text", x=1966, y=88, label= "1966: Highest State Launches",size=2.5, color="royalblue3") +
  annotate("text", x=1985, y=48, label= "1986:\n Challenger \n Explosion",size=2.5, color="indianred3") +
  annotate("text", x=1988.5, y=63, label= "1989: Private Launches Begins",size=2.5, color="grey30") +
  annotate("text", x=2012, y=45, label= "2012: State Launches Faded",size=2.5, color="royalblue3") +
  annotate("text", x=1960, y=71, label= "High failure rates \n in early years",size=2.3,color="lightblue4") +
  labs(title = "US State Launches Falls and Private Launches Rises",
       subtitle = "US State and Private Launches by Success",
       x="Year",
       y="Launches",
       fill="Agency Success")+
  theme_clean()+
  scale_fill_manual("Agency Success", 
                    values = c("State - Failure" = "lightblue", 
                               "State - Success" = "dodgerblue",
                               "Private - Failure" = "grey", 
                               "Private - Success" = "black"))+
  theme(legend.title = element_text( size=8), legend.text=element_text(size=8), legend.background = element_rect(color = NA))

```
state and private launches success/failure rate (spaceX)
NASA fails, budget cut, 
blow stuff up cheaper

